name: Issue to Project Automation

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add issue to project
        uses: octokit/request-action@v2.x
        with:
          route: POST /projects/columns/f75ad846/cards
          mediaType: '{"previews": ["inertia"]}'
          requestBody: '{"note": "Issue: ${{ github.event.issue.title }}\nDescription: ${{ github.event.issue.body }}\nState: ${{ github.event.issue.state }}\nLabels: ${{ toJson(github.event.issue.labels.*.name) }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_ASSEMBLE }}